apiVersion: extensions/v1beta1
kind: Deployment                                          
metadata:
  name: np-frontend
spec:
  replicas: 2                                             
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   
    rollingUpdate: 
      maxUnavailable: 1                                   
      maxSurge: 1                                         
  template:
    metadata:
      labels:
        app: np-frontend                                  
    spec:
      containers:
        - image: djkormo/np-frontend
          imagePullPolicy: Always
          name: np-frontend
          env:
          - name: SA_WEBAPP_API_URL
            value: "http://np-webapp-lb/sentiment/"
          ports:
            - containerPort: 80