apiVersion: v1
kind: Service
metadata:
  name: kuard-health
  labels:
    app: kuard-health
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app: kuard-health
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard-health-deployment
  labels:
    app:  kuard-health
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kuard-health
  template:
    metadata:
      labels:
        app: kuard-health
    spec:
      containers:
      - name: kuard-health
        image: djkormo/kuard
        imagePullPolicy: Always #Always #IfNotPresent
        resources:
          limits:
            cpu: "0.2"
            memory: "100Mi"
          requests:
            cpu: "0.1"
            memory: "50Mi"
        ports:
        - containerPort: 8080
        env:
        - name: APP_VERSION
          value: "1.0"
        livenessProbe:
          httpGet:
            path: /healthy
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3