apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-bg-v1
  labels:
    app: my-app-bg
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-app-bg
      version: v1.0.0
  template:
    metadata:
      labels:
        app: my-app-bg
        version: v1.0.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9101"
    spec:
      containers:
      - name: my-app-bg
        image: djkormo/php-hello
        resources:
          limits:
            cpu: "0.2"
            memory: "100Mi"
          requests:
            cpu: "0.1"
            memory: "50Mi"
        ports:
        - name: http
          containerPort: 80
        - name: probe
          containerPort: 80
        env:
        - name: VERSION
          value: v1.0.0
        - name: DEBUG
          value: "false"  
        livenessProbe:
          httpGet:
            path: /health
            port: probe
          initialDelaySeconds: 60
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: probe
          periodSeconds: 5
