apiVersion: apps/v1
kind: Deployment
metadata:
  name: chess-ai-deployment
  labels:
    app: chess-ai  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chess-ai 
  template:
    metadata:
      labels:
        app: chess-ai
    spec:
      containers:
      - name: chess-ai
        image: djkormo/chess-ai:blue
        imagePullPolicy: Always #Always #IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: APP_VERSION
          value: "2.0"