apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: secret-envvars
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: secret-envvars
    spec:
      containers:
      - name: secret-envvars
        image: djkormo/secrets:envvars
        ports:
        - containerPort: 3000
        env:
        - name: LANGUAGE
          value: "English"
        - name: API_KEY
          value: "123-456-789"