apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: secret-hardcode
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: secret-hardcode
    spec:
      containers:
      - name: secret-hardcode
        image: djkormo/secrets:hardcode
        ports:
        - containerPort: 3000