apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: kubeview
  name: kubeview
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kubeview
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: kubeview
      name: kubeview
    spec:
      containers:
      - image: bencuk/kubeview:latest
        imagePullPolicy: Always
        name: kubeview
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "128M"
            cpu: "0.1"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
status: {}
