apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kubeview
  name: kubeview
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: tcp-8000-8000-sdqbg
    nodePort: 30000
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    k8s-app: kubeview
  sessionAffinity: None
  type: LoadBalancer
status:
