apiVersion: v1
kind: Pod
metadata:
  name: pod-quota-2
spec:
  containers:
  - name: pod-quota-2
    image: redis
    resources:
      limits:
        memory: "1Gi"
        cpu: "800m"      
      requests:
        memory: "700Mi"
        cpu: "400m"
      
