apiVersion: v1
kind: LimitRange
metadata:
  name: limit-mem-cpu-per-container
spec:
  limits:
  - max:
      cpu: "400m"
      memory: "500Mi"
    min:
      cpu: "25m"
      memory: "25Mi"
    default:
      cpu: "50m"
      memory: "50Mi"
    defaultRequest:
      cpu: "30m"
      memory: "30Mi"
    type: Container