apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-php-api
  labels:
    app: apache-php-api
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: apache-php-api
  template:
    metadata:
      labels:
        app: apache-php-api
    spec:
      containers:
      - name: app
        image: djkormo/hpa-example
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "0.15"
            memory: "80Mi"
          requests:
            cpu: "0.1"
            memory: "50Mi"
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 80

          # Intial delay is set to a high value to have a better
          # visibility of the ramped deployment
          initialDelaySeconds: 60
          periodSeconds: 20
