apiVersion: v1
kind: Service
metadata:
  name: my-app-ram
  labels:
    app: my-app-ram
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: my-app-ram