---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-chaos-delete
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-chaos-delete
rules:
- apiGroups: [""]
  resources: ["pods","namespace"]
  verbs:
    - list
    - delete
- apiGroups: ["metrics.k8s.io"]
  resources: [pods","namespace"]
  verbs:
    - get
    - list
    - delete
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-chaos-delete
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-chaos-delete
subjects:
- kind: ServiceAccount
  name: kube-chaos-delete
  namespace: failure
