apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
spec:
  hard:
    pods: "60"
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "5"
    limits.memory: 8Gi
    requests.nvidia.com/gpu: 0